// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: beverage/v1/beverage.proto

package beveragev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeverageType int32

const (
	BeverageType_BEVERAGE_TYPE_UNSPECIFIED BeverageType = 0
	BeverageType_BEVERAGE_TYPE_BEER        BeverageType = 1
	BeverageType_BEVERAGE_TYPE_COCKTAIL    BeverageType = 2
	BeverageType_BEVERAGE_TYPE_SHOTS       BeverageType = 3
)

// Enum value maps for BeverageType.
var (
	BeverageType_name = map[int32]string{
		0: "BEVERAGE_TYPE_UNSPECIFIED",
		1: "BEVERAGE_TYPE_BEER",
		2: "BEVERAGE_TYPE_COCKTAIL",
		3: "BEVERAGE_TYPE_SHOTS",
	}
	BeverageType_value = map[string]int32{
		"BEVERAGE_TYPE_UNSPECIFIED": 0,
		"BEVERAGE_TYPE_BEER":        1,
		"BEVERAGE_TYPE_COCKTAIL":    2,
		"BEVERAGE_TYPE_SHOTS":       3,
	}
)

func (x BeverageType) Enum() *BeverageType {
	p := new(BeverageType)
	*p = x
	return p
}

func (x BeverageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BeverageType) Descriptor() protoreflect.EnumDescriptor {
	return file_beverage_v1_beverage_proto_enumTypes[0].Descriptor()
}

func (BeverageType) Type() protoreflect.EnumType {
	return &file_beverage_v1_beverage_proto_enumTypes[0]
}

func (x BeverageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BeverageType.Descriptor instead.
func (BeverageType) EnumDescriptor() ([]byte, []int) {
	return file_beverage_v1_beverage_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_INCREASING  Status = 1
	Status_STATUS_DECREASING  Status = 2
	Status_STATUS_NO_CHANGE   Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_INCREASING",
		2: "STATUS_DECREASING",
		3: "STATUS_NO_CHANGE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_INCREASING":  1,
		"STATUS_DECREASING":  2,
		"STATUS_NO_CHANGE":   3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_beverage_v1_beverage_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_beverage_v1_beverage_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_beverage_v1_beverage_proto_rawDescGZIP(), []int{1}
}

type Beverage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price            string       `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	BasePrice        string       `protobuf:"bytes,3,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	Name             string       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	PercentageChange int64        `protobuf:"varint,5,opt,name=percentage_change,json=percentageChange,proto3" json:"percentage_change,omitempty"`
	Type             BeverageType `protobuf:"varint,6,opt,name=type,proto3,enum=beverage.v1.BeverageType" json:"type,omitempty"`
	Status           Status       `protobuf:"varint,7,opt,name=status,proto3,enum=beverage.v1.Status" json:"status,omitempty"`
}

func (x *Beverage) Reset() {
	*x = Beverage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beverage_v1_beverage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Beverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beverage) ProtoMessage() {}

func (x *Beverage) ProtoReflect() protoreflect.Message {
	mi := &file_beverage_v1_beverage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beverage.ProtoReflect.Descriptor instead.
func (*Beverage) Descriptor() ([]byte, []int) {
	return file_beverage_v1_beverage_proto_rawDescGZIP(), []int{0}
}

func (x *Beverage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Beverage) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Beverage) GetBasePrice() string {
	if x != nil {
		return x.BasePrice
	}
	return ""
}

func (x *Beverage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Beverage) GetPercentageChange() int64 {
	if x != nil {
		return x.PercentageChange
	}
	return 0
}

func (x *Beverage) GetType() BeverageType {
	if x != nil {
		return x.Type
	}
	return BeverageType_BEVERAGE_TYPE_UNSPECIFIED
}

func (x *Beverage) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type GetBeveragesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBeveragesRequest) Reset() {
	*x = GetBeveragesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beverage_v1_beverage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBeveragesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeveragesRequest) ProtoMessage() {}

func (x *GetBeveragesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beverage_v1_beverage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeveragesRequest.ProtoReflect.Descriptor instead.
func (*GetBeveragesRequest) Descriptor() ([]byte, []int) {
	return file_beverage_v1_beverage_proto_rawDescGZIP(), []int{1}
}

type GetBeveragesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beverages []*Beverage `protobuf:"bytes,1,rep,name=beverages,proto3" json:"beverages,omitempty"`
}

func (x *GetBeveragesResponse) Reset() {
	*x = GetBeveragesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beverage_v1_beverage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBeveragesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeveragesResponse) ProtoMessage() {}

func (x *GetBeveragesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beverage_v1_beverage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeveragesResponse.ProtoReflect.Descriptor instead.
func (*GetBeveragesResponse) Descriptor() ([]byte, []int) {
	return file_beverage_v1_beverage_proto_rawDescGZIP(), []int{2}
}

func (x *GetBeveragesResponse) GetBeverages() []*Beverage {
	if x != nil {
		return x.Beverages
	}
	return nil
}

type CreateBeverageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beverage *Beverage `protobuf:"bytes,1,opt,name=beverage,proto3" json:"beverage,omitempty"`
}

func (x *CreateBeverageRequest) Reset() {
	*x = CreateBeverageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beverage_v1_beverage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBeverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeverageRequest) ProtoMessage() {}

func (x *CreateBeverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beverage_v1_beverage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeverageRequest.ProtoReflect.Descriptor instead.
func (*CreateBeverageRequest) Descriptor() ([]byte, []int) {
	return file_beverage_v1_beverage_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBeverageRequest) GetBeverage() *Beverage {
	if x != nil {
		return x.Beverage
	}
	return nil
}

type CreateBeverageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBeverageResponse) Reset() {
	*x = CreateBeverageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beverage_v1_beverage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBeverageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeverageResponse) ProtoMessage() {}

func (x *CreateBeverageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beverage_v1_beverage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeverageResponse.ProtoReflect.Descriptor instead.
func (*CreateBeverageResponse) Descriptor() ([]byte, []int) {
	return file_beverage_v1_beverage_proto_rawDescGZIP(), []int{4}
}

type UpdateBeverageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beverage *Beverage `protobuf:"bytes,1,opt,name=beverage,proto3" json:"beverage,omitempty"`
}

func (x *UpdateBeverageRequest) Reset() {
	*x = UpdateBeverageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beverage_v1_beverage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBeverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBeverageRequest) ProtoMessage() {}

func (x *UpdateBeverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beverage_v1_beverage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBeverageRequest.ProtoReflect.Descriptor instead.
func (*UpdateBeverageRequest) Descriptor() ([]byte, []int) {
	return file_beverage_v1_beverage_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBeverageRequest) GetBeverage() *Beverage {
	if x != nil {
		return x.Beverage
	}
	return nil
}

type UpdateBeverageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateBeverageResponse) Reset() {
	*x = UpdateBeverageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beverage_v1_beverage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBeverageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBeverageResponse) ProtoMessage() {}

func (x *UpdateBeverageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beverage_v1_beverage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBeverageResponse.ProtoReflect.Descriptor instead.
func (*UpdateBeverageResponse) Descriptor() ([]byte, []int) {
	return file_beverage_v1_beverage_proto_rawDescGZIP(), []int{6}
}

type DeleteBeverageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBeverageRequest) Reset() {
	*x = DeleteBeverageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beverage_v1_beverage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBeverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBeverageRequest) ProtoMessage() {}

func (x *DeleteBeverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beverage_v1_beverage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBeverageRequest.ProtoReflect.Descriptor instead.
func (*DeleteBeverageRequest) Descriptor() ([]byte, []int) {
	return file_beverage_v1_beverage_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBeverageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBeverageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBeverageResponse) Reset() {
	*x = DeleteBeverageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beverage_v1_beverage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBeverageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBeverageResponse) ProtoMessage() {}

func (x *DeleteBeverageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beverage_v1_beverage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBeverageResponse.ProtoReflect.Descriptor instead.
func (*DeleteBeverageResponse) Descriptor() ([]byte, []int) {
	return file_beverage_v1_beverage_proto_rawDescGZIP(), []int{8}
}

var File_beverage_v1_beverage_proto protoreflect.FileDescriptor

var file_beverage_v1_beverage_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x65,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x62, 0x65,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xec, 0x01, 0x0a, 0x08, 0x42, 0x65, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61,
	0x73, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x62, 0x61, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a,
	0x11, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e,
	0x74, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x62, 0x65, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x62, 0x65, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x65, 0x76,
	0x65, 0x72, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x65, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52,
	0x09, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x73, 0x22, 0x4a, 0x0a, 0x15, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x08, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x08, 0x62, 0x65,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x4a, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x08, 0x62, 0x65, 0x76,
	0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x65,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x52, 0x08, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x22, 0x18, 0x0a, 0x16,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x7a, 0x0a, 0x0c, 0x42, 0x65, 0x76,
	0x65, 0x72, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x42, 0x45, 0x56,
	0x45, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x42, 0x45, 0x56, 0x45,
	0x52, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x45, 0x45, 0x52, 0x10, 0x01,
	0x12, 0x1a, 0x0a, 0x16, 0x42, 0x45, 0x56, 0x45, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x43, 0x4f, 0x43, 0x4b, 0x54, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13,
	0x42, 0x45, 0x56, 0x45, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x48,
	0x4f, 0x54, 0x53, 0x10, 0x03, 0x2a, 0x64, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x49, 0x4e, 0x43, 0x52, 0x45, 0x41, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x15,
	0x0a, 0x11, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x45, 0x43, 0x52, 0x45, 0x41, 0x53,
	0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x4e, 0x4f, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x03, 0x32, 0xde, 0x03, 0x0a, 0x0f,
	0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x6a, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x73, 0x12,
	0x20, 0x2e, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76,
	0x31, 0x2f, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x73, 0x12, 0x73, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x22, 0x2e,
	0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x3a, 0x01,
	0x2a, 0x22, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x73, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x12, 0x22, 0x2e, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x12, 0x3a, 0x01, 0x2a, 0x1a, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x65, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x73, 0x12, 0x75, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42,
	0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x22, 0x2e, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x62, 0x65,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x2a, 0x12, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x65,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x43, 0x5a, 0x41,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x65, 0x74, 0x7a,
	0x79, 0x31, 0x2f, 0x62, 0xc3, 0xb8, 0x72, 0x73, 0x62, 0x61, 0x72, 0x2f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x65, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x62, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_beverage_v1_beverage_proto_rawDescOnce sync.Once
	file_beverage_v1_beverage_proto_rawDescData = file_beverage_v1_beverage_proto_rawDesc
)

func file_beverage_v1_beverage_proto_rawDescGZIP() []byte {
	file_beverage_v1_beverage_proto_rawDescOnce.Do(func() {
		file_beverage_v1_beverage_proto_rawDescData = protoimpl.X.CompressGZIP(file_beverage_v1_beverage_proto_rawDescData)
	})
	return file_beverage_v1_beverage_proto_rawDescData
}

var file_beverage_v1_beverage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_beverage_v1_beverage_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_beverage_v1_beverage_proto_goTypes = []interface{}{
	(BeverageType)(0),              // 0: beverage.v1.BeverageType
	(Status)(0),                    // 1: beverage.v1.Status
	(*Beverage)(nil),               // 2: beverage.v1.Beverage
	(*GetBeveragesRequest)(nil),    // 3: beverage.v1.GetBeveragesRequest
	(*GetBeveragesResponse)(nil),   // 4: beverage.v1.GetBeveragesResponse
	(*CreateBeverageRequest)(nil),  // 5: beverage.v1.CreateBeverageRequest
	(*CreateBeverageResponse)(nil), // 6: beverage.v1.CreateBeverageResponse
	(*UpdateBeverageRequest)(nil),  // 7: beverage.v1.UpdateBeverageRequest
	(*UpdateBeverageResponse)(nil), // 8: beverage.v1.UpdateBeverageResponse
	(*DeleteBeverageRequest)(nil),  // 9: beverage.v1.DeleteBeverageRequest
	(*DeleteBeverageResponse)(nil), // 10: beverage.v1.DeleteBeverageResponse
}
var file_beverage_v1_beverage_proto_depIdxs = []int32{
	0,  // 0: beverage.v1.Beverage.type:type_name -> beverage.v1.BeverageType
	1,  // 1: beverage.v1.Beverage.status:type_name -> beverage.v1.Status
	2,  // 2: beverage.v1.GetBeveragesResponse.beverages:type_name -> beverage.v1.Beverage
	2,  // 3: beverage.v1.CreateBeverageRequest.beverage:type_name -> beverage.v1.Beverage
	2,  // 4: beverage.v1.UpdateBeverageRequest.beverage:type_name -> beverage.v1.Beverage
	3,  // 5: beverage.v1.BeverageService.GetBeverages:input_type -> beverage.v1.GetBeveragesRequest
	5,  // 6: beverage.v1.BeverageService.CreateBeverage:input_type -> beverage.v1.CreateBeverageRequest
	7,  // 7: beverage.v1.BeverageService.UpdateBeverage:input_type -> beverage.v1.UpdateBeverageRequest
	9,  // 8: beverage.v1.BeverageService.DeleteBeverage:input_type -> beverage.v1.DeleteBeverageRequest
	4,  // 9: beverage.v1.BeverageService.GetBeverages:output_type -> beverage.v1.GetBeveragesResponse
	6,  // 10: beverage.v1.BeverageService.CreateBeverage:output_type -> beverage.v1.CreateBeverageResponse
	8,  // 11: beverage.v1.BeverageService.UpdateBeverage:output_type -> beverage.v1.UpdateBeverageResponse
	10, // 12: beverage.v1.BeverageService.DeleteBeverage:output_type -> beverage.v1.DeleteBeverageResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_beverage_v1_beverage_proto_init() }
func file_beverage_v1_beverage_proto_init() {
	if File_beverage_v1_beverage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_beverage_v1_beverage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Beverage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beverage_v1_beverage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBeveragesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beverage_v1_beverage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBeveragesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beverage_v1_beverage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBeverageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beverage_v1_beverage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBeverageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beverage_v1_beverage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBeverageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beverage_v1_beverage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBeverageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beverage_v1_beverage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBeverageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beverage_v1_beverage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBeverageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_beverage_v1_beverage_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beverage_v1_beverage_proto_goTypes,
		DependencyIndexes: file_beverage_v1_beverage_proto_depIdxs,
		EnumInfos:         file_beverage_v1_beverage_proto_enumTypes,
		MessageInfos:      file_beverage_v1_beverage_proto_msgTypes,
	}.Build()
	File_beverage_v1_beverage_proto = out.File
	file_beverage_v1_beverage_proto_rawDesc = nil
	file_beverage_v1_beverage_proto_goTypes = nil
	file_beverage_v1_beverage_proto_depIdxs = nil
}
